name: GHCR push
on:
  push:
    branches:
      - main
    tags:
      - v*
env:
  IMAGE_NAME: pgmanager
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
